  <div class="row">
    <div class="col s12">
      <div id="color-usage" class="section scrollspy">
        <h2 class="header">Dockerfiles</h2>
      </div>
    </div>
  </div>

  <div class="divider"></div>

  <div class="row">
    <a class="waves-effect waves-light btn" id="btn_awesome_dockerfile">Awesome Dockerfile</a>
  </div>
  <div class="row">
    <pre class="col s12 deep-orange lighten-5" id="awesome_dockerfile">
      <code class="language-dockerfile">
        FROM node:0.10-onbuild
        MAINTAINER Erik Günther egu@mensa.se

        EXPOSE 3000
      </code>
    </pre>
  </div>

  <div class="divider"></div>

  <div class="row">
    <a class="waves-effect waves-light btn" id="btn_node_onbuild_dockerfile">Node onbuild Dockerfile</a>
  </div>
  <div class="row">
    <pre  class="col s12 deep-orange lighten-5" style="display: none" id="node_onbuild_dockerfile">
      <code class="language-dockerfile">
        FROM node:0.10.38

        RUN mkdir -p /usr/src/app
        WORKDIR /usr/src/app

        ONBUILD COPY package.json /usr/src/app/
        ONBUILD RUN npm install
        ONBUILD COPY . /usr/src/app

        CMD [ "npm", "start" ]
      </code>
    </pre>
  </div>

  <div class="divider"></div>

  <div class="row">
    <a class="waves-effect waves-light btn" id="btn_node_dockerfile">Node Dockerfile</a>
  </div>
  <div class="row">
    <pre class="col s12 deep-orange lighten-5" style="display: none" id="node_dockerfile">
      <code class="language-dockerfile">

        FROM buildpack-deps:jessie

        # verify gpg and sha256: http://nodejs.org/dist/v0.10.31/SHASUMS256.txt.asc
        # gpg: aka "Timothy J Fontaine (Work) <tj.fontaine@joyent.com>"
        # gpg: aka "Julien Gilli <jgilli@fastmail.fm>"

        RUN gpg --keyserver pool.sks-keyservers.net \
        --recv-keys 7937DFD2AB06298B2293C3187D33FF9D0246406D 114F43EE0176B71C7BC219DD50A3051F888C628D

        ENV NODE_VERSION 0.10.38
        ENV NPM_VERSION 2.11.0

        RUN curl -SLO "http://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" \
        && curl -SLO "http://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
        && gpg --verify SHASUMS256.txt.asc \
        && grep " node-v$NODE_VERSION-linux-x64.tar.gz\$" SHASUMS256.txt.asc | sha256sum -c - \
        && tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
        && rm "node-v$NODE_VERSION-linux-x64.tar.gz" SHASUMS256.txt.asc \
        && npm install -g npm@"$NPM_VERSION" \
        && npm cache clear

        CMD [ "node" ]

      </code>
    </pre>
  </div>
  <script type="text/javascript">
    $('#btn_node_dockerfile').click(function() {
      $('#node_dockerfile').toggle("slow");
    });

    $('#btn_node_onbuild_dockerfile').click(function() {
      $('#node_onbuild_dockerfile').toggle("slow");
    });

    $('#btn_awesome_dockerfile').click(function() {
      $('#awesome_dockerfile').toggle("slow");
    });

  </script>

  <%- contentFor('css') %>
  <%- contentFor('js') %>
